"""Renders a shareable spec-card PNG from collected system data using Pillow."""

import os
from datetime import datetime
from PIL import Image, ImageDraw, ImageFont
import system_info as si

# ── Dimensions ────────────────────────────────────────────────────────────────
W        = 1080
PAD      = 40
COL_GAP  = 16
CARD_R   = 12
ROW_H    = 26
CARD_PV  = 18   # card vertical padding
CARD_GAP = 14

# ── Palette ───────────────────────────────────────────────────────────────────
BG       = (11,  11,  18)
CARD_C   = (20,  20,  30)
BORDER_C = (35,  35,  52)
TXT_PRI  = (232, 232, 242)
TXT_SEC  = (100, 100, 155)
TXT_DIM  = (55,  55,  85)

ACCENT = {
    "os":          (240, 98,  146),
    "cpu":         (255, 183, 77),
    "ram":         (100, 181, 246),
    "motherboard": (206, 147, 216),
    "gpu":         (244, 143, 177),
    "storage":     (77,  182, 172),
    "network":     (77,  208, 225),
    "audio":       (255, 204, 128),
}


# ── Font helpers ──────────────────────────────────────────────────────────────

def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    windir = os.environ.get("WINDIR", "C:\\Windows")
    candidates = (
        ("segoeuib.ttf" if bold else "segoeui.ttf",    windir),
        ("arialbd.ttf"  if bold else "arial.ttf",       windir),
        ("DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf", "/usr/share/fonts/truetype/dejavu"),
    )
    for name, base in candidates:
        try:
            return ImageFont.truetype(os.path.join(base, "Fonts", name) if "Windows" in base
                                      else os.path.join(base, name), size)
        except Exception:
            pass
    try:
        return ImageFont.load_default(size=size)
    except Exception:
        return ImageFont.load_default()


# ── Drawing primitives ────────────────────────────────────────────────────────

def _rrect(draw: ImageDraw.Draw, x0, y0, x1, y1, r=CARD_R,
           fill=None, outline=None, width=1):
    draw.rounded_rectangle([x0, y0, x1, y1], radius=r,
                            fill=fill, outline=outline, width=width)


def _section_height(rows) -> int:
    return CARD_PV + 28 + len(rows) * ROW_H + CARD_PV


def _draw_card(draw: ImageDraw.Draw, x, y, w, h,
               key: str, title: str, rows: list[tuple]):
    accent = ACCENT.get(key, (124, 111, 247))
    f_head = _font(13, bold=True)
    f_lbl  = _font(12)
    f_val  = _font(12, bold=True)

    # Card bg
    _rrect(draw, x, y, x + w, y + h, fill=CARD_C)
    # Left accent stripe
    _rrect(draw, x, y, x + 4, y + h, r=3, fill=accent)
    # Subtle card border
    _rrect(draw, x, y, x + w, y + h, fill=None, outline=BORDER_C, width=1)

    # Section title
    draw.text((x + 18, y + CARD_PV), title.upper(), font=f_head, fill=accent)

    cy = y + CARD_PV + 28
    lbl_x = x + 18
    val_x = x + 18 + 168

    for label, value in rows:
        draw.text((lbl_x, cy), str(label)[:26], font=f_lbl, fill=TXT_SEC)
        draw.text((val_x, cy), str(value)[:44], font=f_val, fill=TXT_PRI)
        cy += ROW_H


def _draw_header(draw: ImageDraw.Draw, img: Image.Image, data: dict) -> int:
    f_app    = _font(40, bold=True)
    f_sub    = _font(14)
    f_detail = _font(12)

    y = PAD

    # Logo (duck)
    logo_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logo.png")
    text_x = PAD
    if os.path.exists(logo_path):
        try:
            logo = Image.open(logo_path).convert("RGBA")
            logo = logo.resize((60, 60), Image.LANCZOS)
            img.paste(logo, (PAD, y - 4), logo)
            text_x = PAD + 74
        except Exception:
            pass

    # Purple "DUCCKY" wordmark
    draw.text((text_x, y), "DUCCKY", font=f_app, fill=(160, 140, 255))
    tw = int(draw.textlength("DUCCKY", font=f_app))
    draw.text((text_x + tw + 14, y + 18), "SYSTEM INFORMATION", font=f_sub, fill=TXT_SEC)

    y += 66
    ts = datetime.now().strftime("%Y-%m-%d  %H:%M:%S")
    draw.text((PAD, y), f"Generated  {ts}", font=f_detail, fill=TXT_DIM)

    y += 24
    draw.line([(PAD, y + 8), (W - PAD, y + 8)], fill=BORDER_C, width=1)
    return y + 24


def _draw_footer(draw: ImageDraw.Draw, y: int) -> int:
    f = _font(11)
    draw.text((PAD, y + 16),
              "Generated by Duccky — Modern System Information Viewer",
              font=f, fill=TXT_DIM)
    return y + 44


# ── Section data builder ──────────────────────────────────────────────────────

def _gather(data: dict) -> list[tuple]:
    sections = []

    def add(key, title, rows):
        if rows:
            sections.append((key, title, rows))

    # OS
    o = data.get("os", {})
    rows = []
    if o.get("caption"):   rows.append(("Name",         o["caption"]))
    v, b = o.get("version",""), o.get("build","")
    if v: rows.append(("Version", f"{v}" + (f"  (Build {b})" if b else "")))
    if o.get("architecture"): rows.append(("Architecture", o["architecture"]))
    if o.get("uptime"):       rows.append(("Uptime",       o["uptime"]))
    add("os", "Operating System", rows)

    # CPU
    cpu = data.get("cpu", {})
    rows = []
    if cpu.get("name"):  rows.append(("Name", cpu["name"]))
    mhz = cpu.get("freq_max_mhz", 0)
    if mhz: rows.append(("Max Speed", f"{mhz/1000:.2f} GHz" if mhz > 1000 else f"{mhz:.0f} MHz"))
    pc = cpu.get("cores_physical"); lc = cpu.get("cores_logical")
    if pc: rows.append(("Cores / Threads", f"{pc} physical  /  {lc} logical"))
    if cpu.get("socket"):     rows.append(("Socket",   cpu["socket"]))
    if cpu.get("l3_cache_kb"): rows.append(("L3 Cache", f"{cpu['l3_cache_kb']} KB"))
    add("cpu", "Processor", rows)

    # RAM
    ram = data.get("ram", {})
    rows = [("Total", si.bytes_to_human(ram.get("total", 0))),
            ("Used",  f"{si.bytes_to_human(ram.get('used',0))}  ({ram.get('percent',0):.0f}%)")]
    if ram.get("memory_type"): rows.append(("Type",   ram["memory_type"]))
    if ram.get("speed_mhz"):   rows.append(("Speed",  f"{ram['speed_mhz']} MHz"))
    if ram.get("channels"):    rows.append(("Config", ram["channels"]))
    add("ram", "Memory", rows)

    # Motherboard
    mb = data.get("motherboard", {})
    mb_name = f"{mb.get('manufacturer','')} {mb.get('product','')}".strip()
    if mb_name:
        rows = [("Board", mb_name)]
        bv = f"{mb.get('bios_vendor','')} {mb.get('bios_version','')}".strip()
        if bv:  rows.append(("BIOS",      bv))
        if mb.get("bios_date"): rows.append(("BIOS Date", mb["bios_date"]))
        add("motherboard", "Motherboard", rows)

    # GPU
    gpus = [g for g in data.get("gpu", []) if not g.get("is_virtual")]
    if gpus:
        rows = []
        for g in gpus[:2]:
            rows.append(("GPU", g["name"]))
            if g.get("vram") and g["vram"] != "N/A":
                rows.append(("VRAM", g["vram"]))
            if g.get("driver_version"):
                rows.append(("Driver", g["driver_version"]))
        add("gpu", "Graphics", rows)

    # Displays
    displays = data.get("displays", [])
    if displays:
        rows = []
        for i, disp in enumerate(displays, 1):
            tag = "Primary" if disp.get("primary") else f"Display {i}"
            res = f"{disp['width']}×{disp['height']} @ {disp['refresh']} Hz"
            rows.append((tag, f"{disp['name']}"))
            rows.append((f"  Resolution", res))
        add("gpu", "Displays", rows)

    # Storage
    drives = data.get("storage", [])
    if drives:
        rows = []
        for drv in drives[:4]:
            lbl = drv["mountpoint"]
            if drv.get("model"): lbl += f"  {drv['model'][:22]}"
            if drv.get("drive_type"): lbl += f" [{drv['drive_type']}]"
            rows.append((lbl, f"{si.bytes_to_human(drv['total'])}  —  {drv['percent']:.0f}% used"))
        add("storage", "Storage", rows)

    # Network
    nets = data.get("network", [])
    if nets:
        rows = []
        for a in nets[:3]:
            name = (a["name"][:28] + "…") if len(a["name"]) > 28 else a["name"]
            parts = []
            if a.get("ipv4"): parts.append(a["ipv4"])
            if a.get("speed_mbps"): parts.append(f"{a['speed_mbps']} Mbps")
            rows.append((name, "  ·  ".join(parts) or "Connected"))
        add("network", "Network", rows)

    # Audio
    audio = data.get("audio", [])
    if audio:
        rows = [(d["name"][:36], d.get("status", "")) for d in audio[:2]]
        add("audio", "Audio", rows)

    return sections


# ── Public API ────────────────────────────────────────────────────────────────

def render(data: dict, path: str) -> str:
    """Render spec card to PNG. Returns saved path."""
    sections = _gather(data)
    col_w = (W - 2 * PAD - COL_GAP) // 2

    # Pair sections into rows of 2
    pairs: list[tuple] = []
    i = 0
    while i < len(sections):
        if i + 1 < len(sections):
            pairs.append((sections[i], sections[i + 1]))
            i += 2
        else:
            pairs.append((sections[i], None))
            i += 1

    # Calculate total height
    header_h = 140
    total_h = PAD + header_h
    for s1, s2 in pairs:
        h1 = _section_height(s1[2])
        h2 = _section_height(s2[2]) if s2 else 0
        total_h += max(h1, h2) + CARD_GAP
    total_h += 50  # footer

    # Draw
    img = Image.new("RGB", (W, total_h), BG)
    draw = ImageDraw.Draw(img)

    # Subtle top glow
    for yi in range(160):
        t = 1 - yi / 160
        c = tuple(min(255, BG[j] + int([6, 4, 22][j] * t)) for j in range(3))
        draw.line([(0, yi), (W, yi)], fill=c)

    y = _draw_header(draw, img, data)

    for s1, s2 in pairs:
        h1 = _section_height(s1[2])
        h2 = _section_height(s2[2]) if s2 else 0
        row_h = max(h1, h2)

        _draw_card(draw, PAD, y, col_w, h1, s1[0], s1[1], s1[2])

        if s2:
            _draw_card(draw, PAD + col_w + COL_GAP, y, col_w, h2,
                       s2[0], s2[1], s2[2])

        y += row_h + CARD_GAP

    _draw_footer(draw, y)
    final_h = y + 50
    img = img.crop((0, 0, W, final_h))
    img.save(path, "PNG")
    return path
